name = "sharex-r2-cloudflare-workers"
type = "javascript"
account_id = "7c7d5b0a9ac4491c1e6e5dc8ad142645"
workers_dev = true
route = "r2-sharex.j3fftw.dev/*"
zone_id = "9465114431b9a02d21bfb8a15dff248a"
compatibility_date = "2022-04-22"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[[r2_buckets]]
bucket_name = "sharex-files"
binding = "R2_BUCKET"
